# Twitter Configs
twitter-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - ElasticSearch
  welcome-message: Hello, Microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
#  enable-v2-tweets: false
#  enable-mock-tweets: false
#  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
#  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
#  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}

#twitter-config:
#  debug: true
#  oauth-consumerKey: 8XmIueap8bRWl4SVlxDrjwuSt
#  oauth-consumerSecret: vdr2BATgb95zN7lH2JpqFETSbxS5qzEIkiUT1hOUMHQHFElfMF
#  oauth-accessToken: 1980307216176492548-HADxPdFZZrznUlPFdZTH8xZn7DCSyF
#  oauth-accessTokenSecret: ZyQC8rsF0ouxxF9NY6xvn8hBUdHfATLkdGFqIpSJi4qrO